# Generated by Django 3.2.13 on 2022-07-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='deviceType',
            field=models.CharField(choices=[('PC', 'PC'), ('MOBILE', 'MOBILE'), ('CLOUDMOBILE', 'CLOUDMOBILE')], default='', max_length=20, verbose_name='设备类型'),
        ),
    ]
